### ISSUE TITLE
OTOH... Error resetting password.

### ISSUE THREAD

**Issue by tildebyte** [nhanb/pytaku-old-gae#9]
As subject. This is on my instance @ https://pytaku.quaestor.us
```python
File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_query.py", line 2921, in __query_result_hook yaml_index=yaml, xml_index=xml)
NeedIndexError: no matching index found. recommended index is:
- kind: User
  properties:
  - name: reset_pw_token
  - name: reset_pw_exp
The suggested index for this query is:
- kind: User
  properties:
  - name: reset_pw_token
  - name: reset_pw_exp
```

**Comment by nhanb** [comment]
@tildebyte I've never run into this problem tbh, but looks like you just need to wait: http://stackoverflow.com/a/29807764

**Edit**: maybe try this too if you're using gcloud to deploy: http://stackoverflow.com/a/38987492

I recommend using the [original App Engine SDK](https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.50.zip). It's what I'm still using and having no trouble with.

**Comment by tildebyte** [comment]
OK, cool. I might go back and try to re-deploy using the GAE SDK, but given that it's working well *aside* from the password change thing...
